# 定義内容の詳細は以下のページを参照
# https://backstage.io/docs/features/software-catalog/descriptor-format
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "hama-test"

  # annotations:
  #   backstage.io/techdocs-ref: dir:.  

spec:
  type: service
  owner: "group:default/guests"
  lifecycle: production
